### PR TITLE
Adds ability to pass conditional argument

### PR DESCRIPTION
**Pull request by JonathanWThom**
* As requested in this issue https://github.com/searls/todo_or_die/issues/5, this commit
makes it possible to pass an `if` keyword argument to `TodoOrDie`. A
user can use only `if`, only `by`, or both.

### CODE REVIEW

**Comment by jasonkarns** [comment]
(sorry I haven't looked yet) but can `if` accept a callable, so that we can provide a proc/lambda instead of boolean literal?

**Comment by cpruitt** [comment]
Had a discussion about this topic today. +1 for accepting a callable.

**Comment by JonathanWThom** [comment]
Alright, I _think_ I've updated this to work the way you've suggested. TBH, I don't pass a ton of callables to methods, so it's possible I missed the mark. Happy to get feedback/instruction if it doesn't work as intended : )

**Comment by searls** [comment]
Landed in 0.0.3

**Pull request merged**
