### PR TITLE
Add `warn_by` and `warn_if` options

### LINKED ISSUE #12: Warn under some condition
If the date is nearing, I'd like to get a warning in CI or something so that I can prepare.
Or if ... some condition is _almost_ met, I want to know it's coming.

I hope to work on this but I'm just leaving this issue as a placeholder or… the internet can implement this for me

### PR DESCRIPTION
**Pull request by czj**
We would really benefit from having some warn options.

After discussion in #12 @bobmaerten tried to add the `warn_by` and `warn_if` options.

Closes #12

### CODE REVIEW

**Comment by searls** [comment]
Appreciate this, but did you run `rake`? This project uses [standard](https://github.com/testdouble/standard) for formatting and has tests for its behavior

**Comment by bobmaerten** [comment]
This is just the code I was not eager to send as a pull request. Not ready, not pretty, and not tested.
I'll get back to it when I have some spare time.

**Comment by bobmaerten** [comment]
It seems to have been handled in #14. But there is still a bug as if you only specify `warn_by:` the die_condition I still met, and the program fails instead of warn.

Keep the good job! ;)

**Comment by searls** [comment]
Paging @leequarella!

**Comment by czj** [comment]
Seems to have been fixed.
Thanks a lot everyone !

**Pull request closed without merging**
